language: generic
os: linux
dist: bionic

jobs:
  include:
  - name: Emscripten
    install:
      - ./make.sh browser
      - source deps/emsdk/emsdk_env.sh
    script: cd xplat/web && ./build.sh noserver

  - name: Ubuntu
    install:
      - sudo apt-get update
      - sudo apt-get -y install xorg-dev libfreetype6-dev libvorbis-dev libogg-dev libasound2-dev libpulse-dev cmake
      - ./make.sh native
    script: cd xplat/linux && ./build.sh
    
  - name: Mac OS
    os: osx
    osx_image: xcode11.3
    language: objective-c
    xcode_project: xplat/macos/tadpole.xcodeproj
    xcode_scheme: rostrum-travis
    xcode_destination: platform=macOS
    install:
      - brew install cmake
      - ./make.sh native
    script: cd xplat/macos && ./build.sh

  - name: iOS
    os: osx
    osx_image: xcode11.3
    language: objective-c
    xcode_project: rostrum.xcodeproj
    xcode_scheme: rostrum-travis
    xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
    install:
      - ./make.sh ios
    script: cd xplat/ios && ./build.sh

  - name: Android
    language: android
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - android-26
        - extra-google-m2repository
        - extra-android-m2repository
    install:
      - xplat/android/install-cmake-linux.sh
      - echo y | sdkmanager "ndk;21.0.6113669"
      - echo y | sdkmanager "cmake;3.10.2.4988404"
      - export NDK_ROOT="$ANDROID_HOME/ndk/21.0.6113669"
      - export ANDROID_NDK_HOME="$NDK_ROOT"
      - export PATH="$PATH:$ANDROID_NDK_HOME"
      - export CMAKE_ROOT="$NDK_ROOT/build/cmake"
      - cat "$CMAKE_ROOT/android.toolchain.cmake"
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update
      - sudo apt-get install libstdc++6-4.7-dev -y
      - ./make.sh android
    script: cd xplat/android && ./build.sh
