jobs:
  include:

  - name: "Emscripten"
    language: generic
    os: linux
    dist: bionic
    install:
    - ./make.sh browser
    - source deps/emsdk/emsdk_env.sh
    script: cd xplat/web && ./build.sh noserver

  - name: "Ubuntu":
    language: generic
    os: linux
    dist: bionic
    install:
    - sudo apt-get update
    - sudo apt-get -y install xorg-dev libfreetype6-dev libvorbis-dev libogg-dev libasound2-dev libpulse-dev cmake
    - ./make.sh native
    script: cd xplat/linux && build.sh
