os:
  - linux
language: generic

install:
  - sudo apt-get update
  - sudo apt-get -y install xorg-dev libfreetype6-dev libvorbis-dev libogg-dev libasound2-dev libpulse-dev cmake
  - ./make.sh browser
  - source ./emsdk_env.sh
  - cd xplat/web && ./build.sh noserver
  - cd ../..
  - ./make.sh native
  - cd xplat/linux && ./build.sh

dist: bionic
